# Generated by Django 2.1.2 on 2018-11-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20181119_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrain',
            name='clase',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='retrain',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
