# Generated by Django 2.1.2 on 2018-11-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_image_retrain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retrain',
        ),
        migrations.AddField(
            model_name='image',
            name='clase',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='suggested',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
