# Generated by Django 2.1.2 on 2018-12-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20181119_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.CharField(blank=True, max_length=1000, null=True)),
                ('Timein', models.CharField(blank=True, max_length=1000, null=True)),
                ('Timeout', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
